// let a;
// a = 10;
// console.log(typeof(a),a);

// let string = "this is a string";
// console.log(typeof(string),":",string);

// let boolean = true;
// console.log(boolean);
// console.log("hello world!");

// let number = 10;
// let string = number.toString();
// console.log(typeof(string),number,string);
// let number1 =parseInt(string);
// console.log(number1);

// let n =100;
// console.log(n);

// let a  = 10;
// let b = 20;


// let st = "hello world!";
// let str ="i am ratul";

// let total_string=st + str;
// console.log(total_string);
//.....9.Use template literals to embed variables in a string.


// let strings = "this is number = ";
// let number = 10;

// console.log('this is number =${number}'  );
// let product = "laptop";
// let price = 999.99;

// let advertisement = `The price of the ${product} is $${price}.`;




// console.log(advertisement);

// let mobile = "mobile";
// let prize = "$1000";
// let pp = parseInt(prize);



// console.log(pp);
// let total_amout =`${mobile } prize = ${prize}`
// console.log(total_amout);
// Output: The price of the laptop is $999.99.


//10.Check if a variable is null or undefined.
// var variable = null;
// var variable = undefined;

// if (variable === null || variable === undefined) {
//     console.log('The variable is null or undefined');
//   } else {
//     console.log('The variable is neither null nor undefined');
//   }
  
// 1.Write an if statement to check if a number is positive.
// let positive = 7;
// let nagative = 5;
// if( positive % 2 ==0){
//     console.log("positive number");

// }else{
//     console.log("nagative");
// }

// let number = 0; // Replace 5 with the number you want to check

// if (number > 0) {
//   console.log('The number is positive');
// } else {
//   console.log('The number is not positive');
// }


// let age = 30;

// if(age > 0 & age <= 12 ){
//     console.log("child!");
// }else if(age > 13 && age <= 17){
// console.log("stanger!");

// }else if(age >= 18 && age <= 64){
//     console.log("adult!");
// }else if( age>65 && age <=70){
//     console.log("seneor!");

// }else{
//     console.log("invalid!");
// }
//4.Write a switch statement to handle different cases for days of the week.
// let userform =prompt("enter your number or somethings:");
// console.log(userform);
// let userInput = prompt("Please enter your input:");
// console.log(userInput);


// let i;
// i =prompt ("Enter your number:");
// console.log(i);

// let userInput = prompt("Please enter your name:");
// console.log("Hello, " + userInput + "!");
// let days  =4;


// switch(days ){
//     case 1:
//         console.log("statdays")
//         break;
//     case 2:
//        console.log("suuday");
//        break;
//     case 3:
//         console.log("monday");
//         break;   
//     case 4:
//         console.log("tuesday");
//         break;
//     case 5:
//         console.log("wednessdays");
//         break;
//     case 6:
//         console.log("tusdays");
//         break;
//     case 7:
//         console.log("friday");
//         break
//     default:
//         console.log("invalid days");                

// }



// for( let i = 1; i < 10; i ++){
//     console.log(i);
// }

// let i =1;
// while( i < 100){
//     console.log("hello world!");
//     i++;
// }

// let i =1;
// do{
//     console.log("md yeasin sheikh");
//     i++;
// }while (i <100);

let car={};

car.name= "marcity";
car.brand = "fiat";
car.serial_number = "010293";
car.number ="502";
car.engine = "1000cc";





